### ISSUE TITLE
cannot remove nodes in dynamic layers

### ISSUE THREAD

**Issue by BoySun045** [MIT-SPARK/Spark-DSG#3]
Hi, thank you for sharing the project. 
I'm working on a cpp script to cut the graph into multiple subgraphs. And I'm currently having an issue with removing nodes on the dynamics layers. 

For the static layers, I iterate through all the nodes and use removeNode(NodeId) to remove the node with it's id: 
```
Ptr dsg_ptr = hydra::loadSingleGraph(dsgFilepath);
for (const auto& id_layer_pair : dsg_ptr->layers()) { 
    for(const auto& id_node_pair : id_layer_pair.second->nodes() ) {
      // remove the node 
      dsg_ptr->removeNode(id_node_pair.first);
    }
  }
```
This works well, if I check `dsg_ptr->numNodes()` it returns 0 in every static layers

However, if I use a similar method to remove nodes in the dynamic layers: 
```
  for (const auto& layer_group : dsg_ptr->dynamicLayers()) { 
    for (const auto& prefix_layer_pair : layer_group.second) {
      for(const auto& dsg_node: prefix_layer_pair.second->nodes()){       
        // remove the node
         dsg_ptr->removeNode(dsg_node->id);    
      }
    }
  }
```

It does not work, as I run `dsg_ptr->numNodes()` it returns the same number(which >0) in the dynamic layer as it is before the remove. And another strange observation here is, though the node number stays the same, the number of Edges becomes zero. It looks like dynamics layer is constructed a bit differently, however, I do not have any idea what could be the issue here or how to solve it. 

Could you provide some help with this? Thank you!

**Comment by nathanhhughes** [comment]
Thank you for your interest in our work!  You are correct that the difficulty here is stemming from the difference between the node storage for static and dynamic layers, as well as how we are using this code in Hydra (we haven't had a need to remove dynamic nodes). We've made a few fixes to how the dynamic layer behaves since I last released code to this repo. The relevant changes are in [this](https://github.com/MIT-SPARK/Spark-DSG/tree/feature/update_bindings)  branch, which I'll merge into `main` at some point.

Some additional notes:
- `hasNode` and `getRemovedNodes` do actually work as expected on `main` after a call to `removeNode` for dynamic layers. This is because `removeNode` appropriately marks a node as deleted, but doesn't clear the associated node attributes for the removed node. `numNodes` doesn't change because it looks at the size of the vector containing all the node attributes.  This is fixed in the branch I pointed you to
- You'll want to remove static nodes outside iterating through the nodes as removing a node invalidates the node iterator. This isn't the case for dynamic nodes (we don't actually erase the slot in the vector storing the nodes), but it's probably good practice to do so because we're likely to change how we're storing dynamic nodes in the future
- When iterating through the nodes in a dynamic layer after removing them, you'll want to first check that the current pointer to a node isn't a `nullptr` before using it (if you're on the branch I pointed you to), as deleted nodes will show up as empty slots in the vector containing all the nodes.  This is not the case if you're using the bindings
- The new branch I pointed you to is necessary for making sure saving and loading the DSG to a json file works as expected after deleting dynamic nodes

Please let me know if you have any further questions!

**Comment by BoySun045** [comment]
Hi Nathan! Thank you so much for your quick reply and kind help. 

Yes, I switched to the branch you suggested and it works now. And you are right, I have to check the pointer of the dynamic nodes while iterating after the removal (e.g., visualize dynamic layers). Your notes helped a lot, and I think I can proceed from here. Thank you again!
